### PR TITLE
Remove hrl

### LINKED ISSUE #19: Simplify .travis.yml
Have this working:
```
language: erlang
otp_release:
  - 19.3
  - 20.3
  - 21.3
  - 22.3
  - 23.0
script: make travis
```

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
I started by wanting to remove the .hrl from this lib.

I made the necessary changes for this.

Then I got into a frenzy about modernizing this and making it more maintainable and the result is in sight.

Breaking changes are documented in `MIGRATION.md`.

Also:
* closes #19

### CODE REVIEW

**Review by g-andrade — COMMENTED** [review]
Are we going to drop Travis CI for good?

**Comment by paulo-ferraz-oliveira** [comment]
> Are we going to drop Travis CI for good?

Yes. Do you see any inconvenient?

**Comment by lrascao** [comment]
> Are we going to drop Travis CI for good?

good riddance i say

**Review by g-andrade — APPROVED** [review]

**Comment by lrascao** [comment]
how come this is getting merged with failing tests?

**Comment by g-andrade** [comment]
Well indeed, I hadn't noticed that.. is it a nondeterministic test case, @paulo-ferraz-oliveira ?

**Comment by paulo-ferraz-oliveira** [comment]
It is a non-deterministic test case. It'd been merged (not that it's an excuse for this pull request) in the past, under the same conditions, also.

**Comment by paulo-ferraz-oliveira** [comment]
I re-ran the action. All tests are now passing.

**Pull request merged**
