### PR TITLE
Make HTTPS connections secure by default

### PR DESCRIPTION
**Pull request by g-andrade**
Up until now, no checks were made of the remote certificate:
```erlang
> lhttpc:request("https://self-signed.badssl.com/", "HEAD", [], 5000).
{ok,{{200,"OK"},
     [{"accept-ranges","bytes"},
                .......
      {"server","nginx/1.10.3 (Ubuntu)"}],
     <<>>}}
```

Now they are:
```erlang
> lhttpc:request("https://self-signed.badssl.com/", "HEAD", [], 5000).
{error,{{tls_alert,"bad certificate"}, .......}
```

...unless one explicitly wants to expose their prude bytes to peeping toms:
```erlang
> lhttpc:request("https://self-signed.badssl.com/", "HEAD", [], <<>>, 5000, 
                 [{verify_ssl_cert, false}]).
{ok,{{200,"OK"},
     [{"accept-ranges","bytes"},
                .......
      {"server","nginx/1.10.3 (Ubuntu)"}],
     <<>>}}
```

### CODE REVIEW

**Comment by g-andrade** [comment]
Changes:

- Added
    - missing boot dependencies
- Changed
    - application was rebar3ified while still being usable as a rebar2 dependency
    - application version is now determined from git
    - **HTTPS requests are now secure by default**
- Fixed
    - unintelligibility on which test cases failed (main suite)
    - low test coverage due to broken test cases that prevented others from running

**Review by rjcoelho — COMMENTED** [review]
So we need to periodically update the certificates, correct ? Also do we have a verify_ssl_cert kill switch just in case ?

**Comment by g-andrade** [comment]
> So we need to periodically update the certificates, correct ? 

Yes. Although I'm thinking maybe _certifi_ could be smarter and load the operating system CA bundle (where supported) if it's newer than the one it packs...

> Also do we have a verify_ssl_cert kill switch just in case ?

I don't like the idea of having a kill switch for this. I think it best to leave it to consumers to implement it - different endpoints might have very different tolerance of HTTPS insecurity (e.g. a paying system VS an avatar service.) 

One might then think to do it per pool - but then you've got the issue of the default pool being shared by everyone, and the use of custom pools requiring each consumer to declare it explicitly.

**Comment by rjcoelho** [comment]
There should be a opt-out way to disable it.

**Comment by g-andrade** [comment]
There is one; you can specify it per `:request`.

**Comment by lrascao** [comment]
@rjcoelho perhaps we could create a different component that abstracts this one, that new one would be concerned with resilience, like adding fuses, the killswitch you mentioned, etc, throughts?

I'm concern with simplify adoption since this is used everywhere. First we bump the dependencies, then we turn the "key" on. A new component goes against this.

**Review by paulo-ferraz-oliveira — APPROVED** [review]

**Comment by g-andrade** [comment]
> I'm concern with simplify adoption since this is used everywhere. First we bump the dependencies, then we turn the "key" on. A new component goes against this.

To clarify, this was @rjcoelho 's answer, not an extension of @lrascao 's original comment. Man, was that confusing :)

Holy shit, you can edit someone else's comment?

**Comment by g-andrade** [comment]
I'm good with merging if all of you are too. Tweaks and flags can be added later if we do feel the need for them.

**Comment by lrascao** [comment]
LGTM

**Review by lrascao — APPROVED** [review]

**Comment by g-andrade** [comment]
I've made a [PR](https://github.com/certifi/erlang-certifi/pull/32) to certifi for auto updating the CA bundle. But it's very experimental yet, and subject to approval.
So I'm going ahead with a new lhttpc version for now.

**Pull request merged**
